public class SlowCode {
    public static void main(String[] args) {
        System.out.print("Loading...");
        System.out.println("DONE!");
        if (args.length != 1) {
            System.out.println("Just one argument, buddy!");
            System.exit(1);
        }
        int val = Integer.parseInt(args[0]) - 1;
        Other o = new Other(val);
        System.out.println("=6(MUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(EFGIMUFGIMUGIMUHLSIMUJOYKRLSMUNXOYPQRSTUVWXYZA=6(B@;2CA=6(DCA=6(E");
        System.out.println("Statistics of value " + val + ":");
        System.out.println("Chirpy Number? " + (6 * val % 7 == 0));
        System.out.println("Nirpy Number? " + (val >= 0));
        System.out.println("Schnirpiness Level " + Chirp.schnirpyLevel(val));
        System.out.println("Threat Level: " + o.threatLevel(val));
        System.out.println("DEFCON: " + ((val > 0) ? (val+1)*val/2 : val));
    }
}
